### ISSUE TITLE
Import error Werkzeug library

### ISSUE THREAD

**Issue by ssb95-A** [ChainsawRambo/NJIT-IT490#19]
If I uncommit the following line from app.py in frontend:
**import from werkzeug.security import check_password_hash, generate_password_hash**

I run into the following error and cannot figure out what is causing it:
![WerkzeugError](https://user-images.githubusercontent.com/70778858/95669175-7b0f8700-0b4b-11eb-982c-9b7f87d6285f.JPG)

**Comment by rxt1077** [comment]
I couldn't reproduce this and I uncommented the commented out parts too. Maybe you need to do a fresh `docker-compose build`?
