### ISSUE TITLE
Get Backend ready for midterm deliverables

### ISSUE THREAD

**Issue by mjdroz** [ChainsawRambo/NJIT-IT490#20]

**Comment by ChainsawRambo** [comment]
As long as we get full credit on Milestone 3, we will be good for Midterm professor said. Just waiting on grade for that.

**Comment by mjdroz** [comment]
Sounds good. I thought there was additional components that we needed to add.

**Comment by ChainsawRambo** [comment]
As far as what professor said in class today, no. Just having Milestone 3 objectives completed along with previous ones seems to be what he wants. You can always email him just in case because according to Midterm Deliverables, we have everything done already it seems.

**Comment by ssb95-A** [comment]
**Back End gathers information from data sources, stores information on Database**

The four services are working with each other to **provide a registration and authentication system for users**.

The bold still need to be done for the midterm

**Comment by rxt1077** [comment]
Yeah, that's correct. Your registration form looks good, **Back End** is up and running, **DB** seems to be working fine, as does **Messaging**. Next step is to make an endpoint for the POST request of that form that performs the register action and gets those users in the DB. Looking good group!

**Comment by ChainsawRambo** [comment]
@rxt1077 Anything else specifically that needs to be addressed that we don't already have professor?  Midterm Deliverables as written now still appear to be unclear in some aspects as discussed.

**Comment by rxt1077** [comment]
Based on where you're at now, if you get your register and login forms working you'll have a functioning auth system and be good to go. You're just about there.

**Comment by mjdroz** [comment]
Great! Thank you for the clarification and help.

**Comment by ssb95-A** [comment]
[Cocktail - Google Chrome 2020-10-13 14-54-41.zip](https://github.com/ChainsawRambo/NJIT-IT490/files/5373609/Cocktail.-.Google.Chrome.2020-10-13.14-54-41.zip)

**Comment by mjdroz** [comment]
Backend was revised, no code was changed in the process. I just implemented functions and renamed some variables to decrease readability issues going forward.
