### ISSUE TITLE
Milestone 3 / Midterm Proof of Completion Video

### ISSUE THREAD

**Issue by ChainsawRambo** [ChainsawRambo/NJIT-IT490#21]
[Click hereI](https://youtu.be/2GQnkqli9GI)

![IT 490 Milestone 3 Back End Read and Write Database and Access Database User and Volume](https://user-images.githubusercontent.com/54954995/95788751-1e76ae00-0caa-11eb-8e75-d7f20b51c185.png)

Shouldn't receive an error like in video because record has not been added on your machine yet.  Instead you would receive output like in above screenshot.

As for other objectives, below screenshots.  For all previous Milestone objectives, please refer to other closed issues in repo.

![IT 490 Milestone 3 Documentation for Messaging](https://user-images.githubusercontent.com/54954995/95788899-701f3880-0caa-11eb-9f00-289e2291d03a.png)
![IT 490 Milestone 3 Front End Login Page](https://user-images.githubusercontent.com/54954995/95788912-76151980-0caa-11eb-9bd9-c8c2e94c4cf7.png)
![IT 490 Milestone 3 Front End Register Page](https://user-images.githubusercontent.com/54954995/95788918-79a8a080-0caa-11eb-9b5b-08bcf12f95ea.png)

**Comment by ChainsawRambo** [comment]
Done showing first version of Milestone 3 / Midterm objectives being completed and working.

**Comment by ssb95-A** [comment]
[Cocktail - Google Chrome 2020-10-13 14-54-41.zip](https://github.com/ChainsawRambo/NJIT-IT490/files/5373932/Cocktail.-.Google.Chrome.2020-10-13.14-54-41.zip)
