### ISSUE TITLE
Milestone 4: Minikube is Running

### ISSUE THREAD

**Issue by ChainsawRambo** [ChainsawRambo/NJIT-IT490#27]
Minkube is up and running

**Comment by mjdroz** [comment]
Done, and the "kubectl" command is working as shown below.

![minikube](https://user-images.githubusercontent.com/70978029/97220923-9fea3800-17a2-11eb-9e0c-e8992026d262.PNG)

**Comment by ChainsawRambo** [comment]
Same. The "kubectl" command is working as shown below.
![IT 490 Milestone 4 Minikube Running](https://user-images.githubusercontent.com/54954995/97222097-366b2900-17a4-11eb-914b-36458df4ead3.png)
