### ISSUE TITLE
Work On and Finish Back End for Milestone 2

### ISSUE THREAD

**Issue by mjdroz** [ChainsawRambo/NJIT-IT490#4]

**Comment by ChainsawRambo** [comment]
Sent mock code to be reviewed by Michael and edited to finish this part of milestone 2.  Would have attached code, but cannot add files.

**Comment by mjdroz** [comment]
Finished

**Comment by ChainsawRambo** [comment]
![IT 490 Milestone 2 Front End Working](https://user-images.githubusercontent.com/54954995/94349548-4e1f8800-0013-11eb-95f8-5caccf7f2d82.png)

**Comment by ChainsawRambo** [comment]
![IT 490 Milestone 2 Back-End and Messenger Working](https://user-images.githubusercontent.com/54954995/94349555-6394b200-0013-11eb-9ae3-1e07b4147dd2.png)
